# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app


# Install PyTorch, PennyLane, and Pandas
RUN pip3 install torch pennylane pandas netCDF4

# Make port 8888 available to the world outside this container (for Jupyter Notebook)
EXPOSE 8888

# Run Jupyter Notebook
CMD ["jupyter", "notebook", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--allow-root"]